// Generated by CoffeeScript PHP 1.3.1
(function() {
  var Board;

  Board = (function() {

    function Board(_arg) {
      var dropTemplate, gemTemplate, tileTemplate, _ref;
      _ref = _arg != null ? _arg : {}, tileTemplate = _ref.tileTemplate, dropTemplate = _ref.dropTemplate, gemTemplate = _ref.gemTemplate, this.totalMove = _ref.totalMove, this.scoreRank = _ref.scoreRank;
      this.tileManager = new $Model.TileManager(tileTemplate);
      this.dropManager = new $Model.DropManager(dropTemplate);
      this.gemManager = new $Model.GemManager({
        template: gemTemplate,
        tileManager: this.tileManager,
        dropManager: this.dropManager
      });
      if (this.scoreRank == null) {
        this.scoreRank = [10, 100, 1000];
      }
      if (this.totalMove == null) {
        this.totalMove = 50;
      }
      this.moves = 0;
      this.score = 0;
    }

    Board.prototype.toString = function() {
      var data;
      return data = {
        tileTemplate: this.tileManager.toString(),
        dropTemplate: this.dropManager.toString(),
        gemManager: this.gemManager.toString()
      };
    };

    return Board;

  })();

  $Model.Board = Board;

}).call(this);
