// Generated by CoffeeScript PHP 1.3.1
(function() {
  var DropManager;

  DropManager = (function() {

    function DropManager(_arg) {
      var _ref;
      _ref = _arg != null ? _arg : {}, this.colors = _ref.colors, this.dropRates = _ref.dropRates;
      if (this.colors == null) {
        this.colors = [1, 2, 3, 4, 5, 6];
      }
      if (this.dropRates == null) {
        this.dropRates = {};
      }
    }

    DropManager.prototype.getColors = function() {
      return $Model.clone(this.colors);
    };

    DropManager.prototype._applyDropRate = function(_arg) {
      var chance, col, dropRate, gemParamaters, index, paramater, position, random, _i, _len, _ref, _ref1;
      position = _arg.position;
      gemParamaters = {
        position: position
      };
      col = position.col;
      if (!(this.dropRates[col] != null)) {
        col = -1;
      }
      if (this.dropRates[col] != null) {
        _ref = this.dropRates[col];
        for (paramater in _ref) {
          dropRate = _ref[paramater];
          random = Math.floor(Math.random() * dropRate.chances[0]);
          index = 0;
          _ref1 = dropRate.chances;
          for (index = _i = 0, _len = _ref1.length; _i < _len; index = ++_i) {
            chance = _ref1[index];
            if (random > chance) {
              gemParamaters[paramater] = dropRate.values[index - 1];
              break;
            }
          }
          if (gemParamaters[paramater] == null) {
            gemParamaters[paramater] = dropRate.values[index - 1];
          }
        }
      }
      return gemParamaters;
    };

    DropManager.prototype.drop = function(_arg) {
      var colors, gemParamaters, position;
      position = _arg.position, colors = _arg.colors, gemParamaters = _arg.gemParamaters;
      if (gemParamaters == null) {
        gemParamaters = this._applyDropRate({
          position: position
        });
      }
      if (colors == null) {
        colors = this.colors;
      }
      if (gemParamaters.color == null) {
        gemParamaters.color = colors[Math.floor(Math.random() * colors.length)];
      }
      gemParamaters.position = position;
      return new $Model.Gem(gemParamaters);
    };

    return DropManager;

  })();

  /*
  
  dropRates = 
      0: #cols
          is_lock: 
              chances:[100,50]
              values:[0,1]
  
  
  dm = new DropManager
      colors:6
      dropRates: dropRates
  */


  $Model.DropManager = DropManager;

}).call(this);
