// Generated by CoffeeScript PHP 1.3.1
(function() {
  var Gem;

  Gem = (function() {

    function Gem(_arg) {
      var _ref;
      _ref = _arg != null ? _arg : {}, this.color = _ref.color, this.combo = _ref.combo, this.shield = _ref.shield, this.isLock = _ref.isLock, this.isMystery = _ref.isMystery, this.letter = _ref.letter, this.position = _ref.position;
    }

    if (Gem.color == null) {
      Gem.color = 0;
    }

    if (Gem.combo == null) {
      Gem.combo = 0;
    }

    if (Gem.shield == null) {
      Gem.shield = 0;
    }

    if (Gem.letter == null) {
      Gem.letter = "";
    }

    if (Gem.isLock == null) {
      Gem.isLock = false;
    }

    if (Gem.isMystery == null) {
      Gem.isMystery = false;
    }

    Gem.neighbour = {
      col: [],
      row: []
    };

    Gem.isDistoryed = false;

    Gem.prototype.damage = function() {
      if (this.shield) {
        this.shield -= 1;
      } else if (this.isMystery) {
        this.isMystery = false;
      } else {
        this.isDistoryed = true;
      }
      return this.isDistoryed;
    };

    Gem.prototype.mystery = function() {
      console.log("Need to generate mystery");
      return this.letter = this.letter.substring(1, this.letter);
    };

    return Gem;

  })();

  $Model.Gem = Gem;

}).call(this);
