// Generated by CoffeeScript PHP 1.3.1
(function() {
  var MegaGem;

  MegaGem = (function() {

    function MegaGem(_arg) {
      this.row = _arg.row, this.col = _arg.col;
      if (this.row == null) {
        this.row = 0;
      }
      if (this.col == null) {
        this.col = 0;
      }
      if (this.character == null) {
        this.character = "";
      }
      if (this.shield == null) {
        this.shield = 0;
      }
      if (this.shield_rechage == null) {
        this.shield_rechage = 0;
      }
      if (this.comboResistance == null) {
        this.comboResistance = 0;
      }
    }

    MegaGem.prototype.damage = function(gem) {
      var letter;
      if (gem.combo < this.comboResistance) {
        return false;
      }
      if (this.shield) {
        this.shield -= 1;
        return true;
      }
      if (this.character.length > 1) {
        letter = this.character[0];
        this.character = this.character.substring(1, this.character);
        return letter;
      } else {

      }
    };

    return MegaGem;

  })();

  $Model.MegaGem = MegaGem;

}).call(this);
