// Generated by CoffeeScript PHP 1.3.1
(function() {
  var Tile;

  Tile = (function() {

    function Tile(_arg) {
      var _ref;
      _ref = _arg != null ? _arg : {}, this.isPassable = _ref.isPassable, this.isGemable = _ref.isGemable;
      if (this.isPassable == null) {
        this.isPassable = 0;
      }
      if (this.isGemable == null) {
        this.isGemable = 0;
      }
      if (this.isBossNeighbour == null) {
        this.isBossNeighbour = 0;
      }
      this.range = {
        row: {
          start: 0,
          end: 0,
          bush: []
        },
        col: {
          start: 0,
          end: 0,
          bush: []
        }
      };
    }

    return Tile;

  })();

  $Model.Tile = Tile;

}).call(this);
