// Generated by CoffeeScript PHP 1.3.1
(function() {
  var $Config;

  $Config = {
    colors: ['noColor', 'white', 'green', 'red', 'blue', 'pink', 'orange'],
    combos: ['Idle', 'Combo4', 'Combo5', 'Combo6'],
    col: 8,
    row: 8,
    types: ["col", "row"],
    alternativeType: function(type) {
      if (type === "row") {
        return "col";
      } else {
        return "row";
      }
    }
  };

  window.$Config = $Config;

  /*
  Suggestion
  + Segmented JPEG, to reducec loading memory requirement
  */


}).call(this);
