// Generated by CoffeeScript PHP 1.3.1
(function() {
  var loaded;

  loaded = function() {
    cc.view.adjustViewPort(true);
    cc.view.setDesignResolutionSize(640, 960, cc.ResolutionPolicy.SHOW_ALL);
    cc.view.resizeWithBrowserSize(true);
    return cc.LoaderScene.preload(resource.load, function() {
      return cc.director.runScene(new MainScene());
    }, this);
  };

  if (typeof CoffeeScript !== "undefined" && CoffeeScript !== null) {
    loaded();
  } else {
    cc.game.onStart = loaded;
    cc.game.run();
  }

}).call(this);
