// Generated by CoffeeScript PHP 1.3.1
(function() {
  var resource;

  resource = {
    load: ['res/animation.json', 'res/chapter_1.json', 'res/chapter_2.json', 'res/chapter_3.json', 'res/main.json', 'res/board.plist'],
    res: {
      animationJson: 'res/animation.json',
      chapter1Json: 'res/chapter_1.json',
      chapter2Json: 'res/chapter_2.json',
      chapter3Json: 'res/chapter_3.json',
      mainJson: 'res/main.json',
      boardPlist: 'res/board.plist'
    },
    name: {
      animationJson: 'animation.json',
      chapter1Json: 'chapter_1.json',
      chapter2Json: 'chapter_2.json',
      chapter3Json: 'chapter_3.json',
      mainJson: 'main.json',
      boardPlist: 'board.plist'
    }
  };

  if (typeof window !== "undefined" && window !== null) {
    window.resource = resource;
  }

  resource_ready();

}).call(this);
