{
  "variables":{
    "Transform":[
      1,
      2,
      3,
      4,
      5
    ],
    "number":[
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ]
  },
  "variableDefault":{
    "Transform":"3",
    "number":"0"
  },
  "layers":{
    "body":{
      "variableKeys":[
        "Transform"
      ],
      "objectStates":{
        "1":"res\/graphics\/in-game\/obstacle\/lock\/lock_count_down.png",
        "2":"res\/graphics\/in-game\/effect\/lock_form\/lock_form_01.png",
        "3":"res\/graphics\/in-game\/effect\/lock_form\/lock_form_02.png",
        "4":"res\/graphics\/in-game\/effect\/lock_form\/lock_form_03.png",
        "5":"res\/graphics\/in-game\/obstacle\/lock\/lock.png"
      }
    },
    "gem":{
      "variableKeys":[
        
      ],
      "objectStates":{
        "":"res\/graphics\/in-game\/gem\/blue\/blue_idle.png"
      }
    },
    "number":{
      "variableKeys":[
        "number"
      ],
      "objectStates":[
        "res\/graphics\/graphic_font\/countdown_number\/countdown_number_0.png",
        "res\/graphics\/graphic_font\/countdown_number\/countdown_number_1.png",
        "res\/graphics\/graphic_font\/countdown_number\/countdown_number_2.png",
        "res\/graphics\/graphic_font\/countdown_number\/countdown_number_3.png",
        "res\/graphics\/graphic_font\/countdown_number\/countdown_number_4.png",
        "res\/graphics\/graphic_font\/countdown_number\/countdown_number_5.png",
        "res\/graphics\/graphic_font\/countdown_number\/countdown_number_6.png",
        "res\/graphics\/graphic_font\/countdown_number\/countdown_number_7.png",
        "res\/graphics\/graphic_font\/countdown_number\/countdown_number_8.png",
        "res\/graphics\/graphic_font\/countdown_number\/countdown_number_9.png"
      ]
    }
  },
  "layerHidden":{
    "gem":true
  },
  "animations":{
    "CountDown":[
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/graphics\/board\/lock\/lock_count_down.png",
        "actions":{
          "x":{
            "start":26,
            "tween":"Linear"
          },
          "y":{
            "start":10,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.2,
            "end":1.3
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.2,
            "end":1.3
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0,
        "tag":"number",
        "sprite":"res\/graphics\/board\/lock\/lock_number_00.png",
        "actions":{
          "x":{
            "start":26,
            "tween":"Linear"
          },
          "y":{
            "start":10,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.3,
            "end":2
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.3,
            "end":2
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":2,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0,
        "tag":"gem",
        "sprite":"res\/graphics\/board\/blue\/blue_combo_4.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":-2,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.2,
        "tag":"body",
        "sprite":"res\/graphics\/board\/lock\/lock_count_down.png",
        "actions":{
          "x":{
            "start":26,
            "tween":"Linear"
          },
          "y":{
            "start":10,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1.3,
            "tween":"Linear",
            "startTime":0.2,
            "endTime":0.33333333333333,
            "end":1
          },
          "scaleY":{
            "start":1.3,
            "tween":"Linear",
            "startTime":0.2,
            "endTime":0.33333333333333,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.3,
        "tag":"number",
        "sprite":"res\/graphics\/board\/lock\/lock_number_00.png",
        "actions":{
          "x":{
            "start":26,
            "tween":"Linear"
          },
          "y":{
            "start":10,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":2,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.33333333333333,
            "end":1
          },
          "scaleY":{
            "start":2,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.33333333333333,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":2,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.33333333333333,
        "tag":"body",
        "sprite":"res\/graphics\/board\/lock\/lock_count_down.png",
        "actions":{
          "x":{
            "start":26,
            "tween":"Linear"
          },
          "y":{
            "start":10,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.33333333333333,
        "tag":"number",
        "sprite":"res\/graphics\/board\/lock\/lock_number_00.png",
        "actions":{
          "x":{
            "start":26,
            "tween":"Linear"
          },
          "y":{
            "start":10,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":2,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      }
    ],
    "TramsformLock":[
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/graphics\/board\/lock\/lock_count_down.png",
        "actions":{
          "x":{
            "start":26,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":19.5
          },
          "y":{
            "start":10,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":7.5
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0,
        "tag":"number",
        "sprite":"res\/graphics\/board\/lock\/lock_number_00.png",
        "actions":{
          "x":{
            "start":26,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":19
          },
          "y":{
            "start":10,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":5
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":0
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.16666666666667,
        "tag":"number",
        "sprite":"res\/graphics\/board\/lock\/lock_number_00.png",
        "actions":{
          "x":{
            "start":19,
            "tween":"Linear"
          },
          "y":{
            "start":5,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":0,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"5",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.16666666666667,
        "tag":"body",
        "sprite":"res\/graphics\/board\/effect\/lock_form\/lock_form_01.png",
        "actions":{
          "x":{
            "start":19.5,
            "tween":"Linear",
            "startTime":0.16666666666667,
            "endTime":0.25,
            "end":13
          },
          "y":{
            "start":7.5,
            "tween":"Linear",
            "startTime":0.16666666666667,
            "endTime":0.25,
            "end":5
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"2",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.25,
        "tag":"body",
        "sprite":"res\/graphics\/board\/effect\/lock_form\/lock_form_02.png",
        "actions":{
          "x":{
            "start":13,
            "tween":"Linear",
            "startTime":0.25,
            "endTime":0.33333333333333,
            "end":0
          },
          "y":{
            "start":5,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"3",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.33333333333333,
        "tag":"body",
        "sprite":"res\/graphics\/board\/effect\/lock_form\/lock_form_03.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":5,
            "tween":"Linear",
            "startTime":0.33333333333333,
            "endTime":0.41666666666667,
            "end":0
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"4",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.41666666666667,
        "tag":"body",
        "sprite":"res\/graphics\/board\/lock\/lock.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"5",
          "number":"0"
        },
        "event":""
      }
    ],
    "Initialize":[
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/graphics\/board\/lock\/lock_count_down.png",
        "actions":{
          "x":{
            "start":26,
            "tween":"Linear"
          },
          "y":{
            "start":10,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0,
        "tag":"gem",
        "sprite":"res\/graphics\/board\/blue\/blue_combo_4.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":-1,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      },
      {
        "time":0,
        "tag":"number",
        "sprite":"res\/graphics\/board\/lock\/lock_number_00.png",
        "actions":{
          "x":{
            "start":26,
            "tween":"Linear"
          },
          "y":{
            "start":10,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":2,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Transform":"1",
          "number":"0"
        },
        "event":""
      }
    ]
  },
  "variableLock":{
    "number":true
  }
}