{
  "variableDefault":{
    "number":"0"
  },
  "sounds":[
    
  ],
  "variables":{
    "number":[
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ]
  },
  "layers":{
    "body":{
      "variableKeys":[
        "number"
      ],
      "objectStates":[
        "res\/graphics\/board\/lock\/lock_number_00.png",
        "res\/graphics\/board\/lock\/lock_number_01.png",
        "res\/graphics\/board\/lock\/lock_number_02.png",
        "res\/graphics\/board\/lock\/lock_number_03.png",
        "res\/graphics\/board\/lock\/lock_number_04.png",
        "res\/graphics\/board\/lock\/lock_number_05.png",
        "res\/graphics\/board\/lock\/lock_number_06.png",
        "res\/graphics\/board\/lock\/lock_number_07.png",
        "res\/graphics\/board\/lock\/lock_number_08.png",
        "res\/graphics\/board\/lock\/lock_number_09.png"
      ]
    },
    "bomb":{
      "variableKeys":[
        
      ],
      "objectStates":{
        "":"res\/graphics\/board\/lock\/lock_count_down.png"
      }
    }
  },
  "layerHidden":{
    "bomb":true
  },
  "animations":{
    "Intialize":[
      {
        "time":0,
        "tag":"bomb",
        "sprite":"res\/graphics\/board\/lock\/lock_count_down.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":-1,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "number":"0"
        },
        "event":""
      },
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/graphics\/board\/lock\/lock_number_00.png",
        "actions":{
          "x":{
            "start":-1,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "number":"0"
        },
        "event":""
      }
    ],
    "Countdown":[
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/graphics\/board\/lock\/lock_number_00.png",
        "actions":{
          "x":{
            "start":-1,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.3,
            "end":2
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.3,
            "end":2
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":1,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "number":"0"
        },
        "event":""
      },
      {
        "time":0,
        "tag":"bomb",
        "sprite":"res\/graphics\/board\/lock\/lock_count_down.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.21666666666667,
            "end":1.3
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.21666666666667,
            "end":1.3
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.3,
        "tag":"body",
        "sprite":"res\/graphics\/board\/lock\/lock_number_00.png",
        "actions":{
          "x":{
            "start":-1,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":2,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.33333333333333,
            "end":1
          },
          "scaleY":{
            "start":2,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.33333333333333,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":1,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.33333333333333,
        "tag":"body",
        "sprite":"res\/graphics\/board\/lock\/lock_number_00.png",
        "actions":{
          "x":{
            "start":-1,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":1,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "number":"0"
        },
        "event":""
      }
    ]
  }
}