{
  "variables":{
    "frame":[
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ]
  },
  "variableDefault":{
    "frame":1
  },
  "animations":{
    "shake":[
      {
        "time":0,
        "tag":"top",
        "sprite":"res\/graphics\/board\/bush\/bush_shake_01.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "frame":1
        }
      },
      {
        "time":0,
        "tag":"base",
        "sprite":"res\/graphics\/board\/bush\/bush_base.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":-10,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "frame":1
        },
        "event":""
      },
      {
        "time":0.083333333333333,
        "tag":"top",
        "sprite":"bush_shake_02.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "frame":2
        }
      },
      {
        "time":0.16666666666667,
        "tag":"top",
        "sprite":"bush_shake_03.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "frame":3
        }
      },
      {
        "time":0.25,
        "tag":"top",
        "sprite":"bush_shake_04.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "frame":4
        }
      },
      {
        "time":0.33333333333333,
        "tag":"top",
        "sprite":"bush_shake_05.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "frame":5
        }
      },
      {
        "time":0.41666666666667,
        "tag":"top",
        "sprite":"bush_shake_06.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "frame":6
        }
      },
      {
        "time":0.5,
        "tag":"top",
        "sprite":"bush_shake_07.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "frame":7
        }
      }
    ]
  },
  "layers":{
    "base":{
      "variableKeys":[
        
      ],
      "objectStates":{
        "":"res\/graphics\/board\/bush\/bush_base.png"
      }
    },
    "top":{
      "variableKeys":[
        "frame"
      ],
      "objectStates":{
        "1":"res\/graphics\/board\/bush\/bush_shake_01.png",
        "2":"res\/graphics\/board\/bush\/bush_shake_02.png",
        "3":"res\/graphics\/board\/bush\/bush_shake_03.png",
        "4":"res\/graphics\/board\/bush\/bush_shake_04.png",
        "5":"res\/graphics\/board\/bush\/bush_shake_05.png",
        "6":"res\/graphics\/board\/bush\/bush_shake_06.png",
        "7":"res\/graphics\/board\/bush\/bush_shake_07.png"
      }
    }
  }
}