{
  "variables":{
    "type":[
      "menu",
      "popUpYes",
      "popUpNo",
      "popUpCancel",
      "targetPopupClose",
      "play",
      "no1",
      "me",
      "facebookLogin",
      "facebookLogout",
      "btn_back",
      "btn_main_green",
      "flashcard",
      "tutorialButton",
      "buyLife",
      "askLife",
      "buy5Move",
      "endGame",
      "speaker_yellow",
      "speaker_white",
      "collectFC",
      "reviseGame",
      "playAll"
    ]
  },
  "variableDefault":{
    "type":"playNow"
  },
  "animations":{
    "press":[
      {
        "time":0,
        "tag":"body",
        "sprite":"btn_play.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":0.9
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":0.9
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "text":"playNow"
        }
      },
      {
        "time":0.16666666666667,
        "tag":"body",
        "sprite":"btn_play.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.9,
            "tween":"Linear"
          },
          "scaleY":{
            "start":0.9,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "text":"playNow"
        }
      }
    ],
    "release":[
      {
        "time":0,
        "tag":"body",
        "sprite":"btn_play.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.9,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":1
          },
          "scaleY":{
            "start":0.9,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "text":"playNow"
        }
      },
      {
        "time":0.16666666666667,
        "tag":"body",
        "sprite":"btn_play.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "text":"playNow"
        }
      }
    ]
  },
  "layers":{
    "body":{
      "variableKeys":[
        "type"
      ],
      "objectStates":{
        "menu":"res\/graphics\/ui\/common_button\/btn_setting.png",
        "popUpYes":"res\/graphics\/ui\/common_button\/yes_btn.png",
        "popUpNo":"res\/graphics\/ui\/common_button\/no_btn.png",
        "popUpCancel":"res\/graphics\/ui\/common_button\/button_close_red.png",
        "targetPopupClose":"res\/graphics\/ui\/common_button\/btn_close_green.png",
        "play":"res\/graphics\/ui\/popup_target\/popup_target_play_btn.png",
        "no1":"res\/graphics\/ui\/popup_target\/leaderboar_no1btn.png",
        "me":"res\/graphics\/ui\/popup_target\/leaderboar_mebtn.png",
        "facebookLogin":"res\/graphics\/ui\/popup_setting\/btn_login_fb.png",
        "facebookLogout":"res\/graphics\/ui\/popup_setting\/btn_logout_fb.png",
        "btn_back":"res\/graphics\/ui\/common_button\/btn_back.png",
        "btn_main_green":"res\/graphics\/ui\/common_button\/main_button_green.png",
        "flashcard":"res\/graphics\/ui\/common_button\/btn_flashcard.png",
        "tutorialButton":"res\/graphics\/ui\/popup_setting\/btn_tutorial.png",
        "buyLife":"res\/graphics\/ui\/popup_buy_life\/buy_life_btn.png",
        "askLife":"res\/graphics\/ui\/popup_buy_life\/ask_friend_btn.png",
        "buy5Move":"res\/graphics\/ui\/popup_buy_move\/play_on_btn.png",
        "endGame":"res\/graphics\/ui\/popup_buy_move\/end_game_btn.png",
        "speaker_yellow":"res\/graphics\/ui\/common_icon\/ico_speaker.png",
        "speaker_white":"res\/graphics\/ui\/common_icon\/ico_speaker_1.png",
        "collectFC":"res\/graphics\/flashcard\/flashcard_collect_game\/collect_btn.png",
        "reviseGame":"res\/graphics\/flashcard\/flashcard_collection\/revise_flag.png",
        "playAll":"res\/graphics\/flashcard\/flashcard_collection\/phay_all_btn.png"
      }
    }
  }
}