{
  "variables":{
    "type":[
      "playNow",
      "menu",
      "popUpOk",
      "popUpYes",
      "popUpNo",
      "popUpCancel",
      "targetPopupClose",
      "play",
      "no1",
      "me",
      "facebookLogin",
      "facebookLogout"
    ]
  },
  "variableDefault":{
    "type":"playNow"
  },
  "animations":{
    "press":[
      {
        "time":0,
        "tag":"body",
        "sprite":"btn_play.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":0.9
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":0.9
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "text":"playNow"
        }
      },
      {
        "time":0.16666666666667,
        "tag":"body",
        "sprite":"btn_play.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.9,
            "tween":"Linear"
          },
          "scaleY":{
            "start":0.9,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "text":"playNow"
        }
      }
    ],
    "release":[
      {
        "time":0,
        "tag":"body",
        "sprite":"btn_play.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.9,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":1
          },
          "scaleY":{
            "start":0.9,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "text":"playNow"
        }
      },
      {
        "time":0.16666666666667,
        "tag":"body",
        "sprite":"btn_play.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "text":"playNow"
        }
      }
    ]
  },
  "layers":{
    "body":{
      "variableKeys":[
        "type"
      ],
      "objectStates":{
        "playNow":"res\/graphics\/ui\/panel_start\/btn_play.png",
        "menu":"res\/graphics\/ui\/panel_setting\/buttonSetting.png",
        "popUpOk":"res\/graphics\/ui\/popup\/popUpButtonOk.png",
        "popUpYes":"res\/graphics\/ui\/popup\/popUpButtonYes.png",
        "popUpNo":"res\/graphics\/ui\/popup\/popUpButtonNo.png",
        "popUpCancel":"res\/graphics\/ui\/popup\/popUpButtonClose.png",
        "targetPopupClose":"res\/graphics\/ui\/popup_target\/btn_close.png",
        "play":"res\/graphics\/ui\/popup_target\/play.png",
        "no1":"res\/graphics\/ui\/popup_target\/btn-no1.png",
        "me":"res\/graphics\/ui\/popup_target\/btn_me.png",
        "facebookLogin":"res\/graphics\/ui\/panel_setting\/button\/btn_login.png",
        "facebookLogout":"res\/graphics\/ui\/panel_setting\/button\/btn_logout.png"
      }
    }
  }
}