{
  "variableDefault":{
    "current":"true"
  },
  "sounds":[
    
  ],
  "layers":{
    "current_bg":{
      "variableKeys":[
        "current"
      ],
      "objectStates":{
        "true":"res\/graphics\/flashcard\/flashcard_collection\/current_thumb.png",
        "false":"res\/graphics\/ui\/blank_cell.png"
      }
    },
    "background":{
      "variableKeys":[
        
      ],
      "objectStates":{
        "":"res\/graphics\/flashcard\/flashcard_collection\/chapter_frame_thumb.png"
      }
    }
  },
  "variables":{
    "current":[
      "true",
      "false"
    ]
  },
  "variableLock":{
    "current":true
  },
  "animations":{
    "init":[
      {
        "time":0,
        "tag":"current_bg",
        "sprite":"res\/graphics\/flashcard\/flashcard_collection\/current_thumb.png",
        "actions":[
          
        ],
        "objectState":{
          "current":"true"
        }
      },
      {
        "time":0,
        "tag":"background",
        "sprite":"res\/graphics\/flashcard\/flashcard_collection\/chapter_frame_thumb.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":1,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "current":"true"
        },
        "event":""
      }
    ]
  }
}