{
  "variables":{
    "type":[
      "sfx",
      "voice",
      "music",
      "checkbox"
    ],
    "state":[
      "on",
      "off"
    ]
  },
  "variableDefault":{
    "type":"sfx",
    "state":"on"
  },
  "animations":{
    "press":[
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/ui\/panel_setting\/checkbox\/btn_sfx.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":0.9
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":0.9
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "type":"sfx",
          "state":"on"
        }
      },
      {
        "time":0.16666666666667,
        "tag":"body",
        "sprite":"btn_sfx.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.9,
            "tween":"Linear"
          },
          "scaleY":{
            "start":0.9,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "type":"sfx",
          "state":"on"
        }
      }
    ],
    "release":[
      {
        "time":0,
        "tag":"body",
        "sprite":"btn_sfx.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.9,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":1
          },
          "scaleY":{
            "start":0.9,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "type":"sfx",
          "state":"on"
        }
      },
      {
        "time":0.16666666666667,
        "tag":"body",
        "sprite":"btn_sfx.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "type":"sfx",
          "state":"on"
        }
      }
    ]
  },
  "layers":{
    "body":{
      "variableKeys":[
        "type",
        "state"
      ],
      "objectStates":{
        "sfx,on":"res\/graphics\/ui\/popup_setting\/ico_sfx_on.png",
        "voice,on":"res\/graphics\/ui\/popup_setting\/ico_voice_on.png",
        "music,on":"res\/graphics\/ui\/popup_setting\/ico_music_on.png",
        "sfx,off":"res\/graphics\/ui\/popup_setting\/ico_sfx_off.png",
        "voice,off":"res\/graphics\/ui\/popup_setting\/ico_voice_off.png",
        "music,off":"res\/graphics\/ui\/popup_setting\/ico_music_off.png",
        "checkbox,on":"res\/graphics\/ui\/common_button\/checkbox_check.png",
        "checkbox,off":"res\/graphics\/ui\/common_button\/checkbox_uncheck.png"
      }
    }
  }
}