{
  "variables":{
    "Frames":[
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14"
    ]
  },
  "variableDefault":{
    "Frames":"1"
  },
  "animations":{
    "Combo5":[
      {
        "time":0,
        "tag":"Body",
        "sprite":"combo_5_01.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":1
        }
      },
      {
        "time":0.033333333333333,
        "tag":"Body",
        "sprite":"combo_5_02.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":2
        }
      },
      {
        "time":0.066666666666667,
        "tag":"Body",
        "sprite":"combo_5_03.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":3
        }
      },
      {
        "time":0.1,
        "tag":"Body",
        "sprite":"combo_5_04.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":4
        }
      },
      {
        "time":0.13333333333333,
        "tag":"Body",
        "sprite":"combo_5_05.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":5
        }
      },
      {
        "time":0.16666666666667,
        "tag":"Body",
        "sprite":"combo_5_06.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":6
        }
      },
      {
        "time":0.2,
        "tag":"Body",
        "sprite":"combo_5_07.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":7
        }
      },
      {
        "time":0.23333333333333,
        "tag":"Body",
        "sprite":"combo_5_08.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":8
        }
      },
      {
        "time":0.26666666666667,
        "tag":"Body",
        "sprite":"combo_5_09.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":9
        }
      },
      {
        "time":0.3,
        "tag":"Body",
        "sprite":"combo_5_10.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":10
        }
      },
      {
        "time":0.33333333333333,
        "tag":"Body",
        "sprite":"combo_5_11.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":11
        }
      },
      {
        "time":0.36666666666667,
        "tag":"Body",
        "sprite":"combo_5_12.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":12
        }
      },
      {
        "time":0.4,
        "tag":"Body",
        "sprite":"combo_5_13.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":13
        }
      },
      {
        "time":0.43333333333333,
        "tag":"Body",
        "sprite":"combo_5_14.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "Frames":14
        }
      }
    ]
  },
  "layers":{
    "Body":{
      "variableKeys":[
        "Frames"
      ],
      "objectStates":{
        "1":"res\/graphics\/board\/effect\/combo_5\/combo_5_01.png",
        "2":"res\/graphics\/board\/effect\/combo_5\/combo_5_02.png",
        "3":"res\/graphics\/board\/effect\/combo_5\/combo_5_03.png",
        "4":"res\/graphics\/board\/effect\/combo_5\/combo_5_04.png",
        "5":"res\/graphics\/board\/effect\/combo_5\/combo_5_05.png",
        "6":"res\/graphics\/board\/effect\/combo_5\/combo_5_06.png",
        "7":"res\/graphics\/board\/effect\/combo_5\/combo_5_07.png",
        "8":"res\/graphics\/board\/effect\/combo_5\/combo_5_08.png",
        "9":"res\/graphics\/board\/effect\/combo_5\/combo_5_09.png",
        "10":"res\/graphics\/board\/effect\/combo_5\/combo_5_10.png",
        "11":"res\/graphics\/board\/effect\/combo_5\/combo_5_11.png",
        "12":"res\/graphics\/board\/effect\/combo_5\/combo_5_12.png",
        "13":"res\/graphics\/board\/effect\/combo_5\/combo_5_13.png",
        "14":"res\/graphics\/board\/effect\/combo_5\/combo_5_14.png"
      }
    }
  }
}