{
  "variables":[
    
  ],
  "variableDefault":[
    
  ],
  "sounds":[
    
  ],
  "animations":{
    "combo4":[
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/graphics\/board\/rocket\/rocket_explosion.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ]
      },
      {
        "time":0.083333333333333,
        "tag":"body",
        "sprite":"res\/graphics\/board\/rocket\/rocket_explosion.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ]
      }
    ]
  },
  "layers":{
    "body":{
      "variableKeys":[
        
      ],
      "objectStates":{
        "":"res\/graphics\/board\/rocket\/rocket_explosion.png"
      }
    }
  }
}