{
  "variableDefault":{
    "color":"white"
  },
  "sounds":[
    
  ],
  "variables":{
    "color":[
      "white",
      "green",
      "red",
      "blue",
      "pink",
      "orange"
    ]
  },
  "layers":{
    "halo1":{
      "variableKeys":[
        "color"
      ],
      "objectStates":{
        "white":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_white.png",
        "green":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_green.png",
        "red":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_red.png",
        "blue":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_blue.png",
        "pink":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_pink.png",
        "orange":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_yellow.png"
      }
    },
    "halo2":{
      "variableKeys":[
        "color"
      ],
      "objectStates":{
        "white":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_white.png",
        "green":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_green.png",
        "red":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_red.png",
        "blue":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_blue.png",
        "pink":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_pink.png",
        "orange":"res\/graphics\/in-game\/effect\/combo_idle\/combo5_halo_yellow.png"
      }
    }
  },
  "animations":{
    "Combo5Idle":[
      {
        "time":0,
        "tag":"halo1",
        "sprite":"res\/graphics\/board\/effect\/combo_idle\/combo5_halo_white.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.5,
            "end":360
          },
          "rotationY":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.5,
            "end":360
          },
          "rotation":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.5,
            "end":360
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "color":"white"
        }
      },
      {
        "time":0,
        "tag":"halo2",
        "sprite":"res\/graphics\/board\/effect\/combo_idle\/combo5_halo_white.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.5,
            "end":-360
          },
          "rotationY":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.5,
            "end":-360
          },
          "rotation":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.5,
            "end":-360
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "color":"white"
        }
      },
      {
        "time":3,
        "tag":"halo1",
        "sprite":"res\/graphics\/board\/effect\/combo_idle\/combo5_halo_white.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":360,
            "tween":"Linear"
          },
          "rotationY":{
            "start":360,
            "tween":"Linear"
          },
          "rotation":{
            "start":360,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "color":"white"
        },
        "event":""
      },
      {
        "time":3,
        "tag":"halo2",
        "sprite":"res\/graphics\/board\/effect\/combo_idle\/combo5_halo_white.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":-360,
            "tween":"Linear"
          },
          "rotationY":{
            "start":-360,
            "tween":"Linear"
          },
          "rotation":{
            "start":-360,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "color":"white"
        },
        "event":""
      }
    ]
  },
  "variableLock":{
    "color":true
  }
}