{
  "variables":[
    
  ],
  "variableDefault":[
    
  ],
  "sounds":[
    
  ],
  "layers":{
    "arrow":{
      "variableKeys":[
        
      ],
      "objectStates":{
        "":"res\/graphics\/in-game\/effect\/arrow.png"
      }
    }
  },
  "animations":{
    "hintArrow":[
      {
        "time":0,
        "tag":"arrow",
        "sprite":"res\/graphics\/in-game\/effect\/arrow.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.33333333333333,
            "end":-11.25
          },
          "anchorX":{
            "start":1,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.3,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.33333333333333,
            "end":0.94615384615385
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":270,
            "tween":"Linear"
          },
          "rotationY":{
            "start":270,
            "tween":"Linear"
          },
          "rotation":{
            "start":270,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.33333333333333,
            "end":255
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ],
        "event":""
      },
      {
        "time":0.33333333333333,
        "tag":"arrow",
        "sprite":"res\/graphics\/in-game\/effect\/arrow.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":-11.25,
            "tween":"Linear",
            "startTime":0.33333333333333,
            "endTime":0.35,
            "end":-12.1875
          },
          "anchorX":{
            "start":1,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.94615384615385,
            "tween":"Linear",
            "startTime":0.33333333333333,
            "endTime":0.35,
            "end":1
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":270,
            "tween":"Linear"
          },
          "rotationY":{
            "start":270,
            "tween":"Linear"
          },
          "rotation":{
            "start":270,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ]
      },
      {
        "time":0.35,
        "tag":"arrow",
        "sprite":"res\/graphics\/in-game\/effect\/arrow.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":-12.1875,
            "tween":"Linear",
            "startTime":0.35,
            "endTime":0.56666666666667,
            "end":-24.375
          },
          "anchorX":{
            "start":1,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":270,
            "tween":"Linear"
          },
          "rotationY":{
            "start":270,
            "tween":"Linear"
          },
          "rotation":{
            "start":270,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear",
            "startTime":0.35,
            "endTime":0.56666666666667,
            "end":200
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ]
      },
      {
        "time":0.56666666666667,
        "tag":"arrow",
        "sprite":"res\/graphics\/in-game\/effect\/arrow.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":-24.375,
            "tween":"Linear",
            "startTime":0.56666666666667,
            "endTime":0.75,
            "end":-30
          },
          "anchorX":{
            "start":1,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":270,
            "tween":"Linear"
          },
          "rotationY":{
            "start":270,
            "tween":"Linear"
          },
          "rotation":{
            "start":270,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":200,
            "tween":"Linear",
            "startTime":0.56666666666667,
            "endTime":0.75,
            "end":0
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ],
        "event":""
      },
      {
        "time":0.75,
        "tag":"arrow",
        "sprite":"res\/graphics\/in-game\/effect\/arrow.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":-30,
            "tween":"Linear"
          },
          "anchorX":{
            "start":1,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":270,
            "tween":"Linear"
          },
          "rotationY":{
            "start":270,
            "tween":"Linear"
          },
          "rotation":{
            "start":270,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":0,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ],
        "event":""
      }
    ]
  }
}