{
  "variables":[
    
  ],
  "variableDefault":[
    
  ],
  "animations":{
    "CreateCombo":[
      {
        "time":0,
        "tag":"flare",
        "sprite":"flare.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.2,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.11666666666667,
            "end":0.45
          },
          "scaleY":{
            "start":0.2,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.11666666666667,
            "end":0.45
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.11666666666667,
            "end":45
          },
          "rotationY":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.11666666666667,
            "end":45
          },
          "rotation":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.11666666666667,
            "end":45
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":100,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.11666666666667,
            "end":255
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ]
      },
      {
        "time":0,
        "tag":"ring",
        "sprite":"combo_ring.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.2,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.3,
            "end":0.83
          },
          "scaleY":{
            "start":0.2,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.3,
            "end":0.83
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.3,
            "end":112.5
          },
          "rotationY":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.3,
            "end":112.5
          },
          "rotation":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.3,
            "end":112.5
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ]
      },
      {
        "time":0.11666666666667,
        "tag":"flare",
        "sprite":"flare.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.45,
            "tween":"Linear",
            "startTime":0.11666666666667,
            "endTime":0.3,
            "end":1
          },
          "scaleY":{
            "start":0.45,
            "tween":"Linear",
            "startTime":0.11666666666667,
            "endTime":0.3,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":45,
            "tween":"Linear",
            "startTime":0.11666666666667,
            "endTime":0.3,
            "end":-112.5
          },
          "rotationY":{
            "start":45,
            "tween":"Linear",
            "startTime":0.11666666666667,
            "endTime":0.3,
            "end":-112.5
          },
          "rotation":{
            "start":45,
            "tween":"Linear",
            "startTime":0.11666666666667,
            "endTime":0.3,
            "end":-112.5
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ]
      },
      {
        "time":0.3,
        "tag":"flare",
        "sprite":"flare.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":0.3
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":0.3
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":-112.5,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":-180
          },
          "rotationY":{
            "start":-112.5,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":-180
          },
          "rotation":{
            "start":-112.5,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":-180
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":150
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ]
      },
      {
        "time":0.3,
        "tag":"ring",
        "sprite":"combo_ring.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.83,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":1.2
          },
          "scaleY":{
            "start":0.83,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":1.2
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":112.5,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":180
          },
          "rotationY":{
            "start":112.5,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":180
          },
          "rotation":{
            "start":112.5,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":180
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear",
            "startTime":0.3,
            "endTime":0.48333333333333,
            "end":0
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ]
      },
      {
        "time":0.48333333333333,
        "tag":"flare",
        "sprite":"flare.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.3,
            "tween":"Linear"
          },
          "scaleY":{
            "start":0.3,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":-180,
            "tween":"Linear"
          },
          "rotationY":{
            "start":-180,
            "tween":"Linear"
          },
          "rotation":{
            "start":-180,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":150,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ]
      },
      {
        "time":0.48333333333333,
        "tag":"ring",
        "sprite":"combo_ring.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1.2,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1.2,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":180,
            "tween":"Linear"
          },
          "rotationY":{
            "start":180,
            "tween":"Linear"
          },
          "rotation":{
            "start":180,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":0,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ]
      }
    ]
  },
  "layers":{
    "flare":{
      "variableKeys":[
        
      ],
      "objectStates":{
        "":"res\/graphics\/board\/effect\/flare.png"
      }
    },
    "ring":{
      "variableKeys":[
        
      ],
      "objectStates":{
        "":"res\/graphics\/board\/effect\/combo_ring.png"
      }
    }
  }
}