{
  "variableDefault":{
    "result":"empty"
  },
  "sounds":[
    
  ],
  "variables":{
    "result":[
      "wrong",
      "right",
      "empty"
    ]
  },
  "layers":{
    "result":{
      "variableKeys":[
        "result"
      ],
      "objectStates":{
        "wrong":"res\/graphics\/flashcard\/flashcard_collect_game\/ico_wrong.png",
        "right":"res\/graphics\/flashcard\/flashcard_collect_game\/ico_right.png",
        "empty":false
      }
    }
  },
  "variableLock":{
    "result":true
  },
  "animations":{
    "showResult":[
      {
        "time":0,
        "tag":"result",
        "sprite":"res\/graphics\/flashcard\/flashcard_collect_game\/ico_wrong.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.33333333333333,
            "end":1.5
          },
          "scaleY":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.33333333333333,
            "end":1.5
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.33333333333333,
            "end":255
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "result":"wrong"
        }
      },
      {
        "time":0.33333333333333,
        "tag":"result",
        "sprite":"res\/graphics\/flashcard\/flashcard_collect_game\/ico_wrong.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1.5,
            "tween":"Linear",
            "startTime":0.33333333333333,
            "endTime":0.41666666666667,
            "end":0.9
          },
          "scaleY":{
            "start":1.5,
            "tween":"Linear",
            "startTime":0.33333333333333,
            "endTime":0.41666666666667,
            "end":0.9
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "result":"wrong"
        },
        "event":""
      },
      {
        "time":0.41666666666667,
        "tag":"result",
        "sprite":"res\/graphics\/flashcard\/flashcard_collect_game\/ico_wrong.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.9,
            "tween":"Linear",
            "startTime":0.41666666666667,
            "endTime":0.5,
            "end":1
          },
          "scaleY":{
            "start":0.9,
            "tween":"Linear",
            "startTime":0.41666666666667,
            "endTime":0.5,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "result":"wrong"
        },
        "event":""
      },
      {
        "time":0.5,
        "tag":"result",
        "sprite":"res\/graphics\/flashcard\/flashcard_collect_game\/ico_wrong.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "result":"wrong"
        },
        "event":""
      }
    ],
    "init":[
      {
        "time":0,
        "tag":"result",
        "sprite":"res\/graphics\/flashcard\/flashcard_collect_game\/ico_wrong.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0,
            "tween":"Linear"
          },
          "scaleY":{
            "start":0,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":0,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "result":"wrong"
        },
        "event":""
      }
    ]
  },
  "layerHidden":{
    "answer_bg":true,
    "answer_tag":true
  }
}