{
  "variables":[
    
  ],
  "variableDefault":[
    
  ],
  "sounds":[
    
  ],
  "layers":{
    "background":{
      "variableKeys":[
        
      ],
      "objectStates":{
        "":"res\/graphics\/flashcard\/flashcard_collection\/fc_meter_bg.png"
      }
    },
    "fill":{
      "variableKeys":[
        
      ],
      "objectStates":{
        "":"res\/graphics\/flashcard\/flashcard_collection\/fc_meter_fillbar.png"
      }
    }
  },
  "animations":{
    "init":[
      {
        "time":0,
        "tag":"background",
        "sprite":"res\/graphics\/flashcard\/flashcard_collection\/fc_meter_bg.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ],
        "event":""
      },
      {
        "time":0,
        "tag":"fill",
        "sprite":"res\/graphics\/flashcard\/flashcard_collection\/fc_meter_fillbar.png",
        "actions":{
          "x":{
            "start":1,
            "tween":"Linear"
          },
          "y":{
            "start":-1,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":1,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ],
        "event":""
      }
    ]
  }
}