{
  "variables":{
    "letter":[
      "?",
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "l",
      "m",
      "n",
      "o",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
      "v",
      "w",
      "x",
      "y",
      "z"
    ]
  },
  "variableDefault":{
    "letter":"?"
  },
  "animations":{
    "LetterAppear":[
      {
        "time":0,
        "tag":"body",
        "sprite":"gem_letter_question.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.11666666666667,
            "end":2
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.11666666666667,
            "end":2
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.11666666666667,
            "end":0
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"?"
        }
      },
      {
        "time":0.11666666666667,
        "tag":"body",
        "sprite":"gem_letter_question.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":2,
            "tween":"Linear"
          },
          "scaleY":{
            "start":2,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":0,
            "tween":"Linear",
            "startTime":0.11666666666667,
            "endTime":0.33333333333333,
            "end":255
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"?"
        }
      },
      {
        "time":0.33333333333333,
        "tag":"body",
        "sprite":"gem_letter_a.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":2,
            "tween":"Linear",
            "startTime":0.33333333333333,
            "endTime":0.45,
            "end":1
          },
          "scaleY":{
            "start":2,
            "tween":"Linear",
            "startTime":0.33333333333333,
            "endTime":0.45,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a"
        }
      },
      {
        "time":0.45,
        "tag":"body",
        "sprite":"gem_letter_a.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0.45,
            "endTime":0.51666666666667,
            "end":1.1
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0.45,
            "endTime":0.51666666666667,
            "end":1.1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a"
        }
      },
      {
        "time":0.51666666666667,
        "tag":"body",
        "sprite":"gem_letter_a.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1.1,
            "tween":"Linear",
            "startTime":0.51666666666667,
            "endTime":0.58333333333333,
            "end":1
          },
          "scaleY":{
            "start":1.1,
            "tween":"Linear",
            "startTime":0.51666666666667,
            "endTime":0.58333333333333,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a"
        }
      },
      {
        "time":0.58333333333333,
        "tag":"body",
        "sprite":"gem_letter_a.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a"
        }
      }
    ],
    "FillLetter":[
      {
        "time":0,
        "tag":"body",
        "sprite":"gem_letter_a.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a"
        }
      },
      {
        "time":0,
        "tag":"bubble",
        "sprite":"letter_bubble.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.65,
            "tween":"Linear"
          },
          "scaleY":{
            "start":0.65,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":1,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a"
        }
      },
      {
        "time":0.05,
        "tag":"bubble",
        "sprite":"letter_bubble.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.65,
            "tween":"Linear",
            "startTime":0.05,
            "endTime":0.21666666666667,
            "end":4
          },
          "scaleY":{
            "start":0.65,
            "tween":"Linear",
            "startTime":0.05,
            "endTime":0.21666666666667,
            "end":4
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":1,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear",
            "startTime":0.05,
            "endTime":0.21666666666667,
            "end":0
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a"
        }
      },
      {
        "time":0.21666666666667,
        "tag":"bubble",
        "sprite":"letter_bubble.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":4,
            "tween":"Linear"
          },
          "scaleY":{
            "start":4,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":1,
            "tween":"Linear"
          },
          "opacity":{
            "start":0,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a"
        }
      }
    ],
    "LetterFly":[
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/graphics\/board\/letters\/gem\/gem_letter_a.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.083333333333333,
            "end":80
          },
          "y":{
            "start":0,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.083333333333333,
            "end":80
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a"
        },
        "event":""
      },
      {
        "time":0.083333333333333,
        "tag":"body",
        "sprite":"res\/graphics\/board\/letters\/gem\/gem_letter_a.png",
        "actions":{
          "x":{
            "start":80,
            "tween":"Linear"
          },
          "y":{
            "start":80,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a"
        },
        "event":""
      }
    ],
    "GetLetter":[
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/graphics\/board\/letters\/gem\/gem_letter_question.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.1,
            "end":4
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.1,
            "end":4
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"?"
        },
        "event":""
      },
      {
        "time":0.1,
        "tag":"body",
        "sprite":"res\/graphics\/board\/letters\/gem\/gem_letter_question.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":4,
            "tween":"Linear",
            "startTime":0.1,
            "endTime":0.33333333333333,
            "end":1
          },
          "scaleY":{
            "start":4,
            "tween":"Linear",
            "startTime":0.1,
            "endTime":0.33333333333333,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"?"
        },
        "event":""
      },
      {
        "time":0.33333333333333,
        "tag":"body",
        "sprite":"res\/graphics\/board\/letters\/gem\/gem_letter_question.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"?"
        },
        "event":""
      }
    ]
  },
  "layers":{
    "body":{
      "variableKeys":[
        "letter"
      ],
      "objectStates":{
        "?":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_question.png",
        "a":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_a.png",
        "b":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_b.png",
        "c":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_c.png",
        "d":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_d.png",
        "e":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_e.png",
        "f":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_f.png",
        "g":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_g.png",
        "h":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_h.png",
        "i":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_i.png",
        "j":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_j.png",
        "k":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_k.png",
        "l":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_l.png",
        "m":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_m.png",
        "n":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_n.png",
        "o":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_o.png",
        "p":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_p.png",
        "q":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_q.png",
        "r":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_r.png",
        "s":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_s.png",
        "t":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_t.png",
        "u":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_u.png",
        "v":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_v.png",
        "w":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_w.png",
        "x":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_x.png",
        "y":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_y.png",
        "z":"res\/graphics\/graphic_font\/gem_letters\/main_letter\/gem_letter_z.png"
      }
    }
  },
  "variableLock":{
    "letter":true
  }
}