{
  "variableDefault":{
    "number":"0"
  },
  "sounds":[
    
  ],
  "variables":{
    "number":[
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ]
  },
  "layers":{
    "body":{
      "variableKeys":[
        "number"
      ],
      "objectStates":[
        "res\/graphics\/graphic_font\/score_number\/score_number_0.png",
        "res\/graphics\/graphic_font\/score_number\/score_number_1.png",
        "res\/graphics\/graphic_font\/score_number\/score_number_2.png",
        "res\/graphics\/graphic_font\/score_number\/score_number_3.png",
        "res\/graphics\/graphic_font\/score_number\/score_number_4.png",
        "res\/graphics\/graphic_font\/score_number\/score_number_5.png",
        "res\/graphics\/graphic_font\/score_number\/score_number_6.png",
        "res\/graphics\/graphic_font\/score_number\/score_number_7.png",
        "res\/graphics\/graphic_font\/score_number\/score_number_8.png",
        "res\/graphics\/graphic_font\/score_number\/score_number_9.png"
      ]
    }
  },
  "animations":{
    "scoreAppear":[
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/graphics\/graphic_font\/score_number\/score_number_0.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":0.2,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":1.3
          },
          "scaleY":{
            "start":0.2,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.16666666666667,
            "end":1.3
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.16666666666667,
        "tag":"body",
        "sprite":"res\/graphics\/graphic_font\/score_number\/score_number_0.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1.3,
            "tween":"Linear",
            "startTime":0.16666666666667,
            "endTime":0.2,
            "end":1
          },
          "scaleY":{
            "start":1.3,
            "tween":"Linear",
            "startTime":0.16666666666667,
            "endTime":0.2,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.21666666666667,
        "tag":"body",
        "sprite":"res\/graphics\/graphic_font\/score_number\/score_number_0.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear",
            "startTime":0.2,
            "endTime":0.5,
            "end":60
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.5,
        "tag":"body",
        "sprite":"res\/graphics\/graphic_font\/score_number\/score_number_0.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":60,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear",
            "startTime":0.5,
            "endTime":0.58333333333333,
            "end":0
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "number":"0"
        },
        "event":""
      },
      {
        "time":0.58333333333333,
        "tag":"body",
        "sprite":"res\/graphics\/graphic_font\/score_number\/score_number_0.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":60,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":0,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "number":"0"
        },
        "event":""
      }
    ]
  }
}