{
  "variables":{
    "isDestroyed":[
      "false",
      "true"
    ]
  },
  "variableDefault":{
    "isDestroyed":"false"
  },
  "sounds":[
    
  ],
  "layers":{
    "body":{
      "variableKeys":[
        "isDestroyed"
      ],
      "objectStates":{
        "true":"res\/graphics\/in-game\/hud\/header\/headerEggDestroyed.png",
        "false":"res\/graphics\/in-game\/hud\/header\/headerEgg.png"
      }
    }
  },
  "animations":{
    "dfgdf":[
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/graphics\/board\/hud\/header\/headerEgg.png",
        "actions":{
          "x":{
            "start":-17,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.066666666666667,
            "end":0
          },
          "y":{
            "start":26,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.066666666666667,
            "end":0
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "isDestroyed":"false"
        },
        "event":""
      },
      {
        "time":0.066666666666667,
        "tag":"body",
        "sprite":"res\/graphics\/board\/hud\/header\/headerEgg.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "isDestroyed":"false"
        }
      }
    ]
  }
}