{
  "variables":{
    "letter":[
      "space",
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "l",
      "m",
      "n",
      "o",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
      "v",
      "w",
      "x",
      "y",
      "z"
    ],
    "type":[
      "inactive",
      "active"
    ]
  },
  "variableDefault":{
    "letter":"space",
    "type":"inactive"
  },
  "animations":{
    "FillLetter":[
      {
        "time":0,
        "tag":"body",
        "sprite":"header_letter_a.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":1,
            "tween":"Linear"
          },
          "opacity":{
            "start":200,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.083333333333333,
            "end":0
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a",
          "bubbleDestroyed":0
        }
      },
      {
        "time":0,
        "tag":"bubble",
        "sprite":"lock_count_down.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.033333333333333,
            "end":1.3
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.033333333333333,
            "end":1.3
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a",
          "bubbleDestroyed":0
        }
      },
      {
        "time":0.033333333333333,
        "tag":"bubble",
        "sprite":"lock_count_down.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1.3,
            "tween":"Linear",
            "startTime":0.033333333333333,
            "endTime":0.083333333333333,
            "end":1
          },
          "scaleY":{
            "start":1.3,
            "tween":"Linear",
            "startTime":0.033333333333333,
            "endTime":0.083333333333333,
            "end":1
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a",
          "bubbleDestroyed":0
        }
      },
      {
        "time":0.083333333333333,
        "tag":"bubble",
        "sprite":"shield_break_02.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a",
          "bubbleDestroyed":1
        }
      },
      {
        "time":0.083333333333333,
        "tag":"body",
        "sprite":"header_letter_a.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":1,
            "tween":"Linear"
          },
          "opacity":{
            "start":0,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a",
          "bubbleDestroyed":1
        }
      },
      {
        "time":0.11666666666667,
        "tag":"bubble",
        "sprite":"shield_break_02.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0.11666666666667,
            "endTime":0.15,
            "end":1.3
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0.11666666666667,
            "endTime":0.15,
            "end":1.3
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a",
          "bubbleDestroyed":1
        }
      },
      {
        "time":0.15,
        "tag":"bubble",
        "sprite":"shield_break_02.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1.3,
            "tween":"Linear"
          },
          "scaleY":{
            "start":1.3,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":0,
            "tween":"Linear"
          },
          "rotationY":{
            "start":0,
            "tween":"Linear"
          },
          "rotation":{
            "start":0,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":{
          "letter":"a",
          "bubbleDestroyed":1
        }
      }
    ]
  },
  "layers":{
    "body":{
      "variableKeys":[
        "letter",
        "type"
      ],
      "objectStates":{
        "space,inactive":"res\/graphics\/board\/letters\/header\/header_letter_space.png",
        "a,inactive":"res\/graphics\/board\/letters\/header\/header_letter_a.png",
        "b,inactive":"res\/graphics\/board\/letters\/header\/header_letter_b.png",
        "c,inactive":"res\/graphics\/board\/letters\/header\/header_letter_c.png",
        "d,inactive":"res\/graphics\/board\/letters\/header\/header_letter_d.png",
        "e,inactive":"res\/graphics\/board\/letters\/header\/header_letter_e.png",
        "f,inactive":"res\/graphics\/board\/letters\/header\/header_letter_f.png",
        "g,inactive":"res\/graphics\/board\/letters\/header\/header_letter_g.png",
        "h,inactive":"res\/graphics\/board\/letters\/header\/header_letter_h.png",
        "i,inactive":"res\/graphics\/board\/letters\/header\/header_letter_i.png",
        "j,inactive":"res\/graphics\/board\/letters\/header\/header_letter_j.png",
        "k,inactive":"res\/graphics\/board\/letters\/header\/header_letter_k.png",
        "l,inactive":"res\/graphics\/board\/letters\/header\/header_letter_l.png",
        "m,inactive":"res\/graphics\/board\/letters\/header\/header_letter_m.png",
        "n,inactive":"res\/graphics\/board\/letters\/header\/header_letter_n.png",
        "o,inactive":"res\/graphics\/board\/letters\/header\/header_letter_o.png",
        "p,inactive":"res\/graphics\/board\/letters\/header\/header_letter_p.png",
        "q,inactive":"res\/graphics\/board\/letters\/header\/header_letter_q.png",
        "r,inactive":"res\/graphics\/board\/letters\/header\/header_letter_r.png",
        "s,inactive":"res\/graphics\/board\/letters\/header\/header_letter_s.png",
        "t,inactive":"res\/graphics\/board\/letters\/header\/header_letter_t.png",
        "u,inactive":"res\/graphics\/board\/letters\/header\/header_letter_u.png",
        "v,inactive":"res\/graphics\/board\/letters\/header\/header_letter_v.png",
        "w,inactive":"res\/graphics\/board\/letters\/header\/header_letter_w.png",
        "x,inactive":"res\/graphics\/board\/letters\/header\/header_letter_x.png",
        "y,inactive":"res\/graphics\/board\/letters\/header\/header_letter_y.png",
        "z,inactive":"res\/graphics\/board\/letters\/header\/header_letter_z.png",
        "space,active":"res\/graphics\/board\/letters\/header\/header_letter_space.png",
        "a,active":"res\/graphics\/board\/letters\/gem\/gem_letter_a.png",
        "b,active":"res\/graphics\/board\/letters\/gem\/gem_letter_b.png",
        "c,active":"res\/graphics\/board\/letters\/gem\/gem_letter_c.png",
        "d,active":"res\/graphics\/board\/letters\/gem\/gem_letter_d.png",
        "e,active":"res\/graphics\/board\/letters\/gem\/gem_letter_e.png",
        "f,active":"res\/graphics\/board\/letters\/gem\/gem_letter_f.png",
        "g,active":"res\/graphics\/board\/letters\/gem\/gem_letter_g.png",
        "h,active":"res\/graphics\/board\/letters\/gem\/gem_letter_h.png",
        "i,active":"res\/graphics\/board\/letters\/gem\/gem_letter_i.png",
        "j,active":"res\/graphics\/board\/letters\/gem\/gem_letter_j.png",
        "k,active":"res\/graphics\/board\/letters\/gem\/gem_letter_k.png",
        "l,active":"res\/graphics\/board\/letters\/gem\/gem_letter_l.png",
        "m,active":"res\/graphics\/board\/letters\/gem\/gem_letter_m.png",
        "n,active":"res\/graphics\/board\/letters\/gem\/gem_letter_n.png",
        "o,active":"res\/graphics\/board\/letters\/gem\/gem_letter_o.png",
        "p,active":"res\/graphics\/board\/letters\/gem\/gem_letter_p.png",
        "q,active":"res\/graphics\/board\/letters\/gem\/gem_letter_q.png",
        "r,active":"res\/graphics\/board\/letters\/gem\/gem_letter_r.png",
        "s,active":"res\/graphics\/board\/letters\/gem\/gem_letter_s.png",
        "t,active":"res\/graphics\/board\/letters\/gem\/gem_letter_t.png",
        "u,active":"res\/graphics\/board\/letters\/gem\/gem_letter_u.png",
        "v,active":"res\/graphics\/board\/letters\/gem\/gem_letter_v.png",
        "w,active":"res\/graphics\/board\/letters\/gem\/gem_letter_w.png",
        "x,active":"res\/graphics\/board\/letters\/gem\/gem_letter_x.png",
        "y,active":"res\/graphics\/board\/letters\/gem\/gem_letter_y.png",
        "z,active":"res\/graphics\/board\/letters\/gem\/gem_letter_z.png"
      }
    }
  }
}