{
  "variables":{
    "type":[
      "sendLife",
      "bulb",
      "right",
      "wrong",
      "scroll",
      "infomation",
      "fcIndicatorNumber"
    ]
  },
  "variableDefault":{
    "type":"sendLife"
  },
  "sounds":[
    
  ],
  "animations":[
    
  ],
  "layers":{
    "body":{
      "variableKeys":[
        "type"
      ],
      "objectStates":{
        "sendLife":"res\/graphics\/ui\/common_icon\/ico_send_life.png",
        "bulb":"res\/graphics\/flashcard\/flashcard_collect_game\/ico_bulb.png",
        "right":"res\/graphics\/flashcard\/flashcard_collect_game\/ico_right.png",
        "wrong":"res\/graphics\/flashcard\/flashcard_collect_game\/ico_scroll.png",
        "scroll":"res\/graphics\/flashcard\/flashcard_collect_game\/ico_wrong.png",
        "infomation":"res\/graphics\/flashcard\/flashcard_collection\/fc_info_icon.png",
        "fcIndicatorNumber":"res\/graphics\/flashcard\/flashcard_collection\/fc_number_board.png"
      }
    }
  }
}