{
  "variables":[
    
  ],
  "variableDefault":[
    
  ],
  "sounds":[
    
  ],
  "layers":{
    "body":{
      "variableKeys":[
        
      ],
      "objectStates":{
        "":"res\/graphics\/in-game\/effect\/flare.png"
      }
    }
  },
  "animations":{
    "GetLetter":[
      {
        "time":0,
        "tag":"body",
        "sprite":"res\/graphics\/in-game\/effect\/flare.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.1,
            "end":5
          },
          "scaleY":{
            "start":1,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.1,
            "end":5
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":-20,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.1,
            "end":133
          },
          "rotationY":{
            "start":-20,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.1,
            "end":133
          },
          "rotation":{
            "start":-20,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.1,
            "end":133
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":127.5,
            "tween":"Linear",
            "startTime":0,
            "endTime":0.1,
            "end":255
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ],
        "event":""
      },
      {
        "time":0.1,
        "tag":"body",
        "sprite":"res\/graphics\/in-game\/effect\/flare.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":5,
            "tween":"Linear",
            "startTime":0.1,
            "endTime":0.33333333333333,
            "end":2
          },
          "scaleY":{
            "start":5,
            "tween":"Linear",
            "startTime":0.1,
            "endTime":0.33333333333333,
            "end":2
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":133,
            "tween":"Linear",
            "startTime":0.1,
            "endTime":0.33333333333333,
            "end":270
          },
          "rotationY":{
            "start":133,
            "tween":"Linear",
            "startTime":0.1,
            "endTime":0.33333333333333,
            "end":270
          },
          "rotation":{
            "start":133,
            "tween":"Linear",
            "startTime":0.1,
            "endTime":0.33333333333333,
            "end":270
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ],
        "event":""
      },
      {
        "time":0.33333333333333,
        "tag":"body",
        "sprite":"res\/graphics\/in-game\/effect\/flare.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":2,
            "tween":"Linear"
          },
          "scaleY":{
            "start":2,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":270,
            "tween":"Linear"
          },
          "rotationY":{
            "start":270,
            "tween":"Linear"
          },
          "rotation":{
            "start":270,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":255,
            "tween":"Linear",
            "startTime":0.33333333333333,
            "endTime":0.35,
            "end":0
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ],
        "event":""
      },
      {
        "time":0.35,
        "tag":"body",
        "sprite":"res\/graphics\/in-game\/effect\/flare.png",
        "actions":{
          "x":{
            "start":0,
            "tween":"Linear"
          },
          "y":{
            "start":0,
            "tween":"Linear"
          },
          "anchorX":{
            "start":0.5,
            "tween":"Linear"
          },
          "anchorY":{
            "start":0.5,
            "tween":"Linear"
          },
          "scaleX":{
            "start":2,
            "tween":"Linear"
          },
          "scaleY":{
            "start":2,
            "tween":"Linear"
          },
          "skewX":{
            "start":0,
            "tween":"Linear"
          },
          "skewY":{
            "start":0,
            "tween":"Linear"
          },
          "rotationX":{
            "start":270,
            "tween":"Linear"
          },
          "rotationY":{
            "start":270,
            "tween":"Linear"
          },
          "rotation":{
            "start":270,
            "tween":"Linear"
          },
          "zIndex":{
            "start":0,
            "tween":"Linear"
          },
          "opacity":{
            "start":0,
            "tween":"Linear"
          },
          "r":{
            "start":255,
            "tween":"Linear"
          },
          "g":{
            "start":255,
            "tween":"Linear"
          },
          "b":{
            "start":255,
            "tween":"Linear"
          }
        },
        "objectState":[
          
        ],
        "event":""
      }
    ]
  }
}