{
  "variables":{
    "type":[
      "startPage",
      "menu"
    ]
  },
  "variableDefault":{
    "type":"startPage"
  },
  "animations":[
    
  ],
  "layers":{
    "body":{
      "variableKeys":[
        "type"
      ],
      "objectStates":{
        "startPage":"res\/graphics\/ui\/panel_start\/startLogo.png",
        "menu":"res\/graphics\/ui\/panel_setting\/settingLogo.png"
      }
    }
  }
}