{
  "variables":{
    "backgroundType":[
      "1",
      "2",
      "3",
      "4"
    ]
  },
  "variableDefault":{
    "backgroundType":"1"
  },
  "sounds":[
    
  ],
  "animations":[
    
  ],
  "layers":{
    "background":{
      "variableKeys":[
        "backgroundType"
      ],
      "objectStates":{
        "1":"res\/graphics\/ui\/popup_target\/score_bg_1.png",
        "2":"res\/graphics\/ui\/popup_target\/score_bg_2.png",
        "3":"res\/graphics\/ui\/popup_target\/score_bg_3.png",
        "4":"res\/graphics\/ui\/popup_target\/score_bg_4.png"
      }
    }
  }
}