{
  "variables":{
    "level":[
      1,
      2,
      3,
      4,
      5
    ]
  },
  "variableDefault":{
    "level":1
  },
  "animations":[
    
  ],
  "layers":{
    "body":{
      "variableKeys":[
        "level"
      ],
      "objectStates":{
        "1":"res\/graphics\/board\/shield\/shield_01.png",
        "2":"res\/graphics\/board\/shield\/shield_02.png",
        "3":"res\/graphics\/board\/shield\/shield_03.png",
        "4":"res\/graphics\/board\/shield\/shield_04.png",
        "5":"res\/graphics\/board\/shield\/shield_05.png"
      }
    }
  }
}