// Generated by CoffeeScript PHP 1.3.1
(function() {
  var MainScene;

  MainScene = cc.Scene.extend({
    onEnter: function() {
      this._super();
      this.rootPanel = ccs.uiReader.widgetFromJsonFile(resource.res.mainJson);
      this.addChild(this.rootPanel);
      this.interfaceGui = new InterfaceController(this.rootPanel, resource.name.mainJson);
      this.boardGui = new BoardController(this.interfaceGui);
      this.boardGui._populateBush();
      return this.boardGui._populateGem();
    }
  });

  window.MainScene = MainScene;

}).call(this);
